---
# tasks file for coffeesprout.sshd

- name: ensure OS specifics are included
  include_vars: "{{ item }}"
  with_first_found:
  - "{{ ansible_os_family }}.yml"
  - main.yml
  tags:
  - sshd

- name: ensure issue.net is created
  template:
    src: "{{ ssh_issue_template }}"
    dest: /etc/issue.net
    owner: 0
    group: 0
    mode: '0644'
  tags:
  - sshd

- name: ensure SSHD configuration is installed
  lineinfile:
    dest: "{{ sshd_config_file | default('/etc/ssh/sshd_config') }}"
    regexp: "^{{ item.name }}"
    line: "{{ item.name }} {{ item.value }}"
    state: present
    validate: '/usr/sbin/sshd -t -f %s'
    backup: True
  with_items:
  - "{{ sshd_default_options }}"
  - "{{ sshd_custom_options }}"
  - "{{ sshd_platform_options }}"
  register: sshd_config_changed
  tags:
  - sshd


- name: Restart sshd
  service:
    name: sshd
    state: reloaded
  when: 'sshd_config_changed.changed and sshd_jail_name is not defined'
  tags:
    - molecule-notest

- name: Restart jailed sshd
  service:
    name: sshd
    state: reloaded
    args: "-j {{ sshd_jail_name }}"
  when: 'sshd_config_changed.changed and sshd_jail_name is defined'
  tags:
    - molecule-notest

- name: Generate documentation
  include_tasks: documentation.yml
  when: doc_generate | default(true)
  tags:
    - docs
    - documentation
